Work with CRUD Post
RafaelKhammadeev/PetProject pull request #6
Opened 2023-04-11 08:03 UTC by RafaelKhammadeev

Close next items:
- User should be able to create a draft Article with title and rich text content
- User should be able to publish draft article

2023-04-17 09:34 UTC, RasimKhusaenov requested changes

2023-04-17 09:34 UTC, RasimKhusaenov commented on .github/workflows/main.yml
> +          sudo apt-get -yqq install libpq-dev
Do you need it?

2023-04-17 09:34 UTC, RasimKhusaenov commented on .github/workflows/main.yml
> +        image: postgres:11
Why 11?

2023-04-17 09:34 UTC, RasimKhusaenov commented on app/controllers/posts_controller.rb
> +    @posts = @user.posts
Guest user can't see posts now, yeah?

2023-04-17 09:34 UTC, RasimKhusaenov commented on app/views/layouts/application.html.erb
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
Redundant?

2023-04-17 09:34 UTC, RasimKhusaenov commented on app/views/posts/_form.html.erb
> +<%= form_with(model: post, url:[user, post]) do |form| %>
```suggestion
<%= form_with [user, post] do |form| %>
```

2023-04-17 09:34 UTC, RasimKhusaenov commented on app/views/posts/show.html.erb
> +<div class="card" style="width: 18rem;">
It is bad practice to use tag `style`

2023-04-17 09:34 UTC, RasimKhusaenov commented on app/views/users/index.html.erb
> +    <% next if user == current_user %>
You should do it in controller

2023-04-17 09:34 UTC, RasimKhusaenov commented on db/migrate/20230314211757_create_posts.rb
> +      t.string :description
You shouldn't change existing migrations

2023-04-17 21:01 UTC, RafaelKhammadeev commented on .github/workflows/main.yml
> +          sudo apt-get -yqq install libpq-dev
I think, no

2023-04-18 10:57 UTC, RafaelKhammadeev commented on app/views/posts/index.html.erb
> +    <% end %>
I think it was better, so I do it in next PR

2023-04-18 21:12 UTC, RafaelKhammadeev commented on app/views/users/index.html.erb
> +    <% next if user == current_user %>
hm, yes cool idea, thanks

2023-05-02 09:43 UTC, RasimKhusaenov requested changes

2023-05-02 09:43 UTC, RasimKhusaenov commented on app/views/users/index.html.erb
> +      <td><%= link_to "#{user.name} #{user.surname}", user_path(user) %></td>
How about use decorator for it?
```suggestion
      <td><%= link_to user.full_name, user_path(user) %></td>
```

2023-05-02 09:43 UTC, RasimKhusaenov commented on app/controllers/users_controller.rb
> +    @users = User.where.not(id: current_user)
```suggestion
    @users = User.excluding(current_user)
```

2023-05-02 09:43 UTC, RasimKhusaenov commented on app/policies/users/post_policy.rb
> +      true if record&.user_id == user.id
Does it work?

2023-05-02 09:43 UTC, RasimKhusaenov commented on config/routes.rb
> +    namespace :users do
It seems incorrect

2023-06-14 09:29 UTC, closed without merging